### ISSUE TITLE
Root Path appears in NR APM

### ISSUE THREAD

**Issue by sb8244** [newrelic/elixir_agent#147]
**Describe the bug**

When setting a transaction name using `set_transaction_name/1`, the result comes into New Relic UI as "Root Path". We've tried the names `"Elixir.Api.Method.FrontendInstallations.Index"` and `"/Elixir.Api.Method.FrontendInstallations.Index"`. The data appears to make it to the Transactions event correctly in New Relic Insights.

**before and after the `/`**
![image](https://user-images.githubusercontent.com/1231659/66873066-87cbc000-ef75-11e9-9651-721bb3ff2569.png)

```
          "event": {
            "framework_name": "/Phoenix/PortalWeb.FrontController/execute",
            "custom_name": "/Elixir.Api.Method.FrontendInstallations.Index",
            "name": "WebTransaction/Elixir.Api.Method.FrontendInstallations.Index",
            "timestamp": 1571171661879
          }
```

**Environment**

* Elixir & Erlang version (`elixir -v`):
```
Erlang/OTP 21 [erts-10.1.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.7.3 (compiled with Erlang/OTP 19)
```

That compiled with looks weird, but I don't think it's related

* Agent version (`mix deps | grep new_relic_agent`):
1.12.0

**Comment by binaryseed** [comment]
I looked into this and it turns out that the UI itself expects there to be > 2 segments (separated by `/`) in the metric name, but in this case it is only 2, which the UI turns into "Root path": 

`WebTransaction/Elixir.Api.Method.FrontendInstallations.Index`

If you hadn't set a custom transaction name, it would have selected the `framework_name` and wound up with the metric name:

`WebTransaction/Phoenix/PortalWeb.FrontController/execute`

So to solve this easily, you can stick another "segment" in the name

In the agent, i should try to be a bit smarter and always stick an extra segment in there

**Comment by sb8244** [comment]
Easy fix. Thanks!
