### ISSUE TITLE
erlang tracing

### ISSUE THREAD

**Issue by sasa1977** [newrelic/elixir_agent#271]
While browsing through the code I noticed that the monitor agent [sets up erlang trace](https://github.com/newrelic/elixir_agent/blob/d86b04913ec58182ab0d7dbd697d816847c1aa95/lib/new_relic/transaction/monitor.ex#L25) to the instrumented process. From what I can tell, this is done for the purpose of catching spawned tasks and poolboy transactions, to make the transaction traces more detailed.

Unfortunately I feel that this approach is too aggressive. As mentioned [at the end of trace doc](http://erlang.org/doc/man/erlang.html#trace-3):

> Each process can only be traced by one tracer. Therefore, attempts to trace an already traced process fail.

This means that as a developer I can't trace instrumented process myself, which limits my options when troubleshooting the production. Moreover, the current solution feels overly naive, because there are other ways how I can start related child processes, (e.g. `Supervisor.start_child`).

Therefore, I'd like to be able to opt-out of erlang tracing. Ideally, a different kind of API would be supported which would allow clients to hook up instrumentation with some existing transaction, for example something along the lines of:

```elixir
# inside an instrumented transaction
parent = self()

Task.start_link(fn ->
  NewRelic.inside_transaction(parent)
  # ...
end)
```

This would require a bit more manual work, but on the upside it doesn't require tracing a process, and it can handle a much wider range of scenarios than currently supported.

**Comment by binaryseed** [comment]
Thanks for this (and for the books!). I've explored a variety techniques for cross process tracking including erlang tracing, `seq_trace` and others. I actually have a large reactor in progress to move away from erlang tracing for transaction tracking, though it still uses tracing to generate process spawns. 

I've optimized for ease of use generally, to cover most cases at the expense of the power user who knows how to use these low level tools.

Along side the refactor however, it'll be possible to add a way to opt out of using the erlang tracer (or disable it temporarily) without losing the core functionality of the agent. A function for manual connection would also be a simple addition.

I'd be happy to explore this topic with you in further detail if you are open to it!

**Comment by sasa1977** [comment]
Thanks for the quick response! I'm definitely open to discussing this further. Let me know how can I help.

**Comment by binaryseed** [comment]
Ok! I got a PR up with the refactor I talked about... https://github.com/newrelic/elixir_agent/pull/284

In my testing, this is a pretty solid performance improvement and the nice thing is that you can disable erlang tracing and that won't interrupt cross-process Transaction tracking, only process span generation...

**Comment by sasa1977** [comment]
Thanks!

I can't say I can understand the full scope of changes, partially b/c the PR is large and involved, and partly because I'm not very familiar with the existing code. One thing that caught my eye is the usage in `GenServer.start` in sidecar. I'd say that this is (almost) always not a good pattern, b/c it can lead to leaking processes. A process should always be linked to its parent. I wonder if these sidecar processes are properly cleaned up.

From what I can tell, to disable tracing it would be enough to invoke `NewRelic.disable_erlang_trace` at the app startup, and then no tracing will take place, right?

When tracing is disabled, how can I manually add other processes to the transaction? For example, suppose that from a rest or graphql request I spawn additional processes (e.g. tasks, genservers, etc), and I want the duration of those to be included in the transaction? What's the procedure for that?

Finally, unrelated to this issue, but I've noticed that you're using `httpc` as the client. I vaguely remember that httpc had some issues (like e.g. occasional deadlocks). Perhaps that has been fixed in newer Erlang versions, but I personally avoid using httpc in production code. Since the agent communicates frequently with the server, I'd recommend a 3rd party http client, such as [mint](https://hexdocs.pm/mint/) or [finch](https://hexdocs.pm/finch/Finch.html).

> this is a pretty solid performance improvement

Is this because of the reduced tracing?

**Comment by ademirovic** [comment]
Thank for the changes @binaryseed.
I work with @sasa1977 on a project and have tried the `1.23.0-rc.3` version on a small example app.
There are differences in data reported to New Relic depending if erlang trace is enabled or disabled.

Results when erlang trace is enabled:
- Distributed tracing:
![enanbled_distributed_tracing](https://user-images.githubusercontent.com/3205719/97029521-d2efba00-155d-11eb-964d-c6eef829dd53.png)
- Transaction trace:
![enabled_transaction](https://user-images.githubusercontent.com/3205719/97029636-003c6800-155e-11eb-946e-a6f5410540d1.png)
- Trace details:
![enabled_trace_details](https://user-images.githubusercontent.com/3205719/97029688-121e0b00-155e-11eb-9341-66a91adbea23.png)

Results when erlang trace is disabled:
- Distributed tracing:
![disabled_distributed_tracing](https://user-images.githubusercontent.com/3205719/97029775-2e21ac80-155e-11eb-8886-baf36135940d.png)
- Transaction trace:
![disabled_transaction](https://user-images.githubusercontent.com/3205719/97029827-3e398c00-155e-11eb-927b-5c5c8bac0ad6.png)
- Trace details:
![disabled_trace_details](https://user-images.githubusercontent.com/3205719/97029861-47c2f400-155e-11eb-9f85-2d714965f466.png)

Summary:
- When erlang trace is enabled, we get a much better breakdown of data on the same query
- When erlang trace is disabled, transaction trace does not show any useful information

**Comment by binaryseed** [comment]
Thanks for your feedback!

> `GenServer.start`

Generally, I always follow the rule regarding linking. I found here however, that there were a few things that pushed me to avoid the link.

1) I never want an unexpected bug in the agent to negatively impact the main app. So I don't want the 2-way exit signal propagation... I do want 1 way exit signals so the first thing the sidecar does is monitor the originating process, and the down message triggers the sidecar to finish and shut down.

2) Initially I did this with a `DynamicSupervisor` but found that it had a significant performance penalty under load since there's a decent amount of coordination happening. A sidecar is started _very_ often (1 per http request), and it blocks, so I want the initialization to happen as quickly as possible.

> disable tracing

If you _never_ want tracing on, I could make a configuration option. The impact would be that traces won't include any process spawns. It's also _currently_ missing function tracing but I will fix that shortly.

> manually add other processes to the transaction

So, `erlang:trace` isn't involved in connecting processes at all anymore. It works the same wether it's on or off. There isn't a function that lets you connect an arbitrary process yet, but one could be added...

The way processes are connected now involves reading `$callers` to detect if we're in a `Task`, and using `$ancestors` after that to detect `GenServer` spawns. This lookup happens once and is "cached" in the pdict after that to minimize the cost.

Will your connection use cases be covered by that or would you still want the manual connection function?

> `httpc`

Some time ago I adopted `httpc` for a few reasons. 

1) The rate of HTTP requests is known, small and static. 1 per "Harvester" (ie: data type) per cycle. There are 10s of requests made per minute to report data up to New Relic. 

2) I'm confident SSL is properly configured and tested

3) No dependencies. When I made this choice, `mint` was still in it's early days. I will log a task to look into it again and see if I can migrate...

> performance imrpvement

This refactor removes a few patterns that had the potential to turn into a bottleneck under load.

1) `:erlang.trace` got message queue backup under load
2) The global ets transaction collection (vs the per-transaction sidecar) got heavy usage from lots of processes

**Comment by sasa1977** [comment]
> If you _never_ want tracing on, I could make a configuration option.

Yeah, this is what I'd prefer. As you've seen yourself, tracing can introduce some perf penalty, and as I mentioned originally it prevents live debugging. Also, I'm not clear what is tracing still used for?

> The impact would be that traces won't include any process spawns.

This seems to contradict the following statement:

> So, `erlang:trace` isn't involved in connecting processes at all anymore.

Am I misunderstanding something?

> It works the same wether it's on or off.

According to the [experiments by @ademirovic](https://github.com/newrelic/elixir_agent/issues/271#issuecomment-715452436), it seems that the behaviour differs depending on whether tracing is on or off (disabled by invoking `NewRelic.disable_erlang_trace` at app startup).

> The way processes are connected now involves reading `$callers`

Unlike tracing, I think that this is a good solution. It will work for descendants, but not for processes started elsewhere in the supervision tree (e.g. a Task started under another dynamic supervisor), so I still think it could be useful to have the option to manually add and remove a code block to another transaction. This could also be used in e.g. GenServer call handlers to get a finer grained breakdown.

> I will log a task to look into it again and see if I can migrate...

Perhaps just adding an option to provide a custom http callback module would be enough. For this you'd need to abstract the contract (i.e. define a behaviour), and support setting a custom callback module, e.g. through app env. I think this should work fine as long as no http requests are made before the app starts.

> Generally, I always follow the rule regarding linking. I found here however, that there were a few things that pushed me to avoid the link.

I guess these are valid reasons, and the solution should work. I'd include a code comment explaining the reason, because the approach is not standard.

I wonder how will this work at scale though. We'll end up with 2x amount of processes, which itself can affect the CPU and memory usage of the system under load.

You mentioned some problems with ets. Not sure how much did you explore this venue, but with some trickery they can be pretty fast. For example, if a single table is a bottleneck, a quick remedy is to use a small shard of tables (e.g. 10 or 100). Also, make sure to set both read & write concurrency to true if there are multiple simultaneous reads & writes (I noticed that the tables created in the new PR use only read concurrency, is that intentional?).

Using a `duplicate_bag` instead of `bag` can also do wonders. For example, one option could be to insert measuring events in a duplicate bag (e.g. operation foo started at x, operation bar stopped at y), using root pid as the key, and then post-process these events after the transaction is done (or when the process terminates) from a single global GenServer (or a small constant pool of such), possibly discarding some transactions when the queue grows large. That way you can ensure the constant usage of resources (# of processes & ets tables), while minimizing the agent's impact on the system performance during the overload periods.

**Comment by binaryseed** [comment]
> behaviour differs depending on whether tracing is on or off

Part of this is a bug that I'm pushing a fix for.... The bug meant that function tracers were getting dropped.

The thing that `erlang:trace` still provides is the collection of Process spawns themselves. That lets a Transaction Trace have a visual indication the process activity inside the Transaction. This has come in handy many times before when someone doesn't realize for example how many process spawns are happening. Function traces alone don't reveal this.

Turning off the agent's usage `erlang:trace` will mean we don't collect process spawn spans, but the function trace activity will remain.

> problems with `ets`

I should be clearer, there weren't significant problems with `ets`. It's been quite impressive really. I use many of the optimizations you mentioned, `duplicate_bag`, some sharding, etc. The problem is that some kind of optimizations that I want to do aren't possible when collecting everything in a global store. For example, I want to limit the number of trace segments we collect in a given transaction. Collected globally, determining the current number of segments requires a heavy operation, but collected per-transaction, it's nearly nothing.

> manual linking

I'll get this capability in...

Thanks for diving into this with me, I appreciate you taking a close look and asking hard questions!

**Comment by binaryseed** [comment]
And yes, the `ets` tables used by the "Sidecar" system are going to be read heavy with intermittent single writes. That seemed like a case for `read_concurrency` but not `write_concurrency`...

Do you think there's an advantage to using `duplicate_bag` even if I never expect more than one object per key?

**Comment by sasa1977** [comment]
> For example, I want to limit the number of trace segments we collect in a given transaction.

Perhaps [update_counter](http://erlang.org/doc/man/ets.html#update_counter-3) could help with that.

> Do you think there's an advantage to using `duplicate_bag` even if I never expect more than one object per key?

Since you're using sets, I don't think so.

**Comment by binaryseed** [comment]
There's a few other reasons why I'm still confident the "Sidecar" approach is an improvement..
* Process usage overall doesn't change - both the Sidecar and the `ets` backed strategies use 1 additional process per Transaction - the Sidecar keeps it around the whole duration and completes the work inside it. The `ets` strategy still needs to spawn a process at the end of the Transaction to complete & report without blocking the Transaction process itself.
* Memory copying is improved - the Sidecar avoids a significant amount of memory copying by collecting and completing the work inside a single process. The `ets` strategy by its nature copies all the Transaction data at the end when pulling it from `ets` to complete.

**Comment by sasa1977** [comment]
The thing with ets is that you can get away with a small constant pool of reporting processes, instead of needing one extra process per each transaction. Basically, the transaction processes (such as http request handlers) store data in ets (which is typically faster than sending a message to another process), while the reporters are responsible for aggregating the data.

With such approach, the impact that metrics introduce on the system performance & resource usage is significantly reduced, and that's what I'd personally prefer to get from a metrics library. In addition, using a constant pool of processes provides the opportunity to actively manage overload by delaying metrics aggregation or shedding (dropping) some metrics. Thus, when the system is overloaded, the metrics processes don't cause extra strain, and we're still able to ship some sample of metrics at near real-time.

You're correct that there's one extra copying involved with ETS, but I wouldn't worry too much about it. In general, I expect that the amount of data per transaction is relatively small (a few dozens, or maybe lower hundreds of relatively simple entries). Sure, this will introduce some extra latency in metrics, but I don't expect it will be significant. It takes a few minutes before shipped metrics are visible on the newrelic site, and from what I understand, they are anyway not shipped by the agent immediately. So any minor extra delay, which I'd expect to be in the microseconds or a single-digit milliseconds area, should be irrelevant. 

In fact, because it's an off-heap structure, ETS might cause less pressure on the GC, and in turn might prove to cause less CPU & memory pressure. See [this article](https://www.theerlangelist.com/article/reducing_maximum_latency) for example where ETS helps significantly reducing the tail percentile latencies due to reduced GC pressure.

To be clear, I'm not saying that ETS is definitely better. Obviously this requires some amount of experimenting and measuring, and I'm positive you already done a lot of work in that area. That being said, I'm skeptical about how current design of one extra process per each transaction scales, and how it affects the performance of the system during the periods of increased load. 

My clients work at a smaller scale, so this is likely not a practical problem, unlike tracing of every transaction, which is IMO always problematic. But either way I feel that any design with uncontrolled concurrency will cause problems at larger scale, and that the approaches which rely on a small constant pool of processes (possibly, but not necessarily, backed by ETS) should be evaluated.

**Comment by binaryseed** [comment]
I have been load testing this and have found good results.. I'll collect some of that data and share it... Looking at GC pressure is a good idea too, I haven't explored that in my comparisons yet.

One thing of note is that the agent isn't purely a "metrics" library - we do a handful of tasks that are better categorized as APM - we collect things like Transaction events, Transaction traces, Distributed traces, etc. If we were metrics-only, we would basically not have this whole "Sidecar" system. At some point we might put together a purely metrics system based on OpenTelemetry with a New Relic exporter, but that's not the goal of this particular library. At the high end of scale, that would be the lowest impact strategy.

To contextualize this portion of the code that's changing, it's the code focused on the Transaction event & tracing portion. There's another subsystem that's responsible for aggregation - that uses a fixed set of processes that "harvest" the particular data types and report them on intervals.

Another optimization I have in mind with the Sidecar is to put overload protections at the beginning - and not even start a Sidecar over a max concurrency level - that'd provide the most load shedding possible since we don't even collect the data past a certain threshold (i'd just report a few basic metrics in that case)

I'll share the load testing results sometime soon :) Thanks!

**Comment by sasa1977** [comment]
> Another optimization I have in mind with the Sidecar is to put overload protections at the beginning - and not even start a Sidecar over a max concurrency level

I think this is a great idea! It would address my main concern of the agent further worsening the system behaviour during overload. 

A slight downside is that by deciding to discard metrics early we lose the opportunity to "catch up" (if the increased load is just a short burst, the agent could actually ship all data with a slight delay).

**Comment by tsloughter** [comment]
I'd been thinking about the future possibility that an agent like this could be on top of OpenTelemetry.

The OpenTelemetry provides the sort of interface @sasa1977 mentions in your first post while a user could include an additional auto instrumentation library like this New Relic agent.

**Comment by binaryseed** [comment]
In the long run, New Relic is all-in on OpenTelemetry (https://newrelic.com/solutions/opentelemetry), and is embracing that as the preferred way to collect data. So in this version of the future, there might not be anything _New Relic_ on "top" of OpenTelemetry, but there could be a package that auto-instruments via `telemetry` & wires that directly into OpenTelemetry. I think all that would be needed then is `newrelic/opentelemetry-exporter-erlang`.

New Relic still has our language agents (like this one) which does lots of auto-instrumentation (via `telemetry`) & sends data to our backends, and we'll support these for quite some time still. That's what I'm focused on here & continue to use in all my production services.
