### ISSUE TITLE
bugs reported

### ISSUE THREAD

**Issue by katekordnejad** [newrelic/elixir_agent#280]
two separate issues with the NewRelic agent for elixir:1. When attempting to monitor functions in our Broadway jobs, we begin to see the NewRelic agent fail to complete all traces. Many traces do complete, but others are left open. With the rate of throughput, this quickly balloons memory to ~13GB, making the BEAM unresponsive.2. Ecto Telemetry raises UnsupportedEctoAdapter, even though we're using Postgrex. Oddly, we get reporting for a short time before this occurs.

**Comment by binaryseed** [comment]
Hi there, we're going to need a bit more information about the context here before we can begin to investigate - the issue template lays out what information is needed. Also ideally these should be reported as individual tickets since they seem unrelated.

I'm going to close this in the hope that 2 targeted tickets with the necessary information can be opened!

Thanks!
