### ISSUE TITLE
Include NEW_RELIC_RULES_IGNORE_URL_REGEXES

### ISSUE THREAD

**Issue by mayalces** [newrelic/elixir_agent#52]
**Is your feature request related to a problem? Please describe.**
We have paths for `health-checks` and `swagger` documentation which we don't want to report to New Relic.

**Describe the solution you'd like**
It would be nice to include an env variable like `NEW_RELIC_RULES_IGNORE_URL_REGEXES`, which allows to have a list of regexes in a comma-separated string to be ignored.

Another option could be a route option like `newrelic_ignore`.

**Comment by sb8244** [comment]
If new relic checked private.newrelic_ignore in the Conn, it would be possible to create a plug in your app to set that for the desired routes. That seems easier to setup than regexes.

**Comment by binaryseed** [comment]
Lost track of this one..

I think setting a value in the `conn` might not work since we suggest putting the New Relic plug as early as possible in the pipeline, so it's probably already tracking the transaction.

I think a possible way to tackle this is to provide a function like `NewRelic.ignore_transaction()` that will basically cancel the tracking of the current transaction, and you can put that wherever it's needed.
